-- Introspección de `tickets` y `bitacora` — NO modifica nada, solo lee el
-- catálogo de Postgres.
--
-- Existe porque estas dos tablas se crearon a mano en el SQL Editor de
-- Supabase y su DDL nunca se versionó: el repositorio solo tiene los
-- `alter table` que las fueron parchando después. Sin el DDL real no se
-- puede levantar el sistema desde cero ni integrarlo en IRP, y tampoco hay
-- forma de saber si QA y Producción divergieron.
--
-- Cómo usarlo: pegar TODO el bloque de la sección A en el SQL Editor de
-- Supabase (una sola corrida, un solo resultado) y copiar la salida. De ahí
-- sale `sql_schema_tickets_bitacora.sql`. Correrlo en QA y también en
-- Producción: comparar las dos salidas es lo único que prueba si hay deriva
-- de esquema.
--
-- La sección B trae los mismos datos en queries sueltos, por si se quiere
-- revisar un aspecto puntual sin leer el volcado completo.

-- ══════════════════════════════════════════════════════════════════════
--  SECCIÓN A · Volcado completo en un solo resultado
-- ══════════════════════════════════════════════════════════════════════
-- Devuelve (seccion, tabla, orden, linea). Las líneas de 1-COLUMNAS ya
-- vienen con formato de DDL para poder pegarlas casi tal cual.

with objetivo as (
  select c.oid, c.relname, c.relrowsecurity, c.relforcerowsecurity
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  -- ÚNICO lugar donde se elige qué tablas mirar. Las cuatro están en la
  -- misma situación: se usan en producción y no tienen DDL versionado.
  -- Para mirar otra tabla, agregarla aquí y el resto del query la incluye solo.
  where n.nspname = 'public'
    and c.relname in ('tickets', 'bitacora', 'cortes', 'empleados')
),
columnas as (
  select
    o.relname as tabla,
    lpad(a.attnum::text, 3, '0') as orden,
    format(
      '%s %s%s%s%s',
      rpad(quote_ident(a.attname), 18),
      format_type(a.atttypid, a.atttypmod),
      case a.attidentity
        when 'a' then ' generated always as identity'
        when 'd' then ' generated by default as identity'
        else ''
      end,
      case
        when ad.adbin is not null and a.attidentity = ''
        then ' default ' || pg_get_expr(ad.adbin, ad.adrelid)
        else ''
      end,
      case when a.attnotnull then ' not null' else '' end
    ) as linea
  from pg_attribute a
  join objetivo o on o.oid = a.attrelid
  left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
  where a.attnum > 0 and not a.attisdropped
),
constraints as (
  -- p=PK, u=UNIQUE, f=FK, c=CHECK. pg_get_constraintdef devuelve el texto
  -- exacto, ya listo para un `alter table ... add constraint`.
  select
    o.relname as tabla,
    con.contype::text || '-' || con.conname as orden,
    con.conname || ' → ' || pg_get_constraintdef(con.oid) as linea
  from pg_constraint con
  join objetivo o on o.oid = con.conrelid
),
indices as (
  -- Incluye los índices que Postgres crea solo para PK/UNIQUE; al escribir
  -- el DDL final no hay que repetirlos como `create index`.
  select i.tablename as tabla, i.indexname as orden, i.indexdef as linea
  from pg_indexes i
  join objetivo o on o.relname = i.tablename
  where i.schemaname = 'public'
),
rls_estado as (
  select
    o.relname as tabla,
    '000' as orden,
    'row level security: ' || case when o.relrowsecurity then 'ACTIVADA' else 'DESACTIVADA' end
      || case when o.relforcerowsecurity then ' (forzada)' else '' end as linea
  from objetivo o
),
rls_politicas as (
  select
    p.tablename as tabla,
    p.policyname as orden,
    format(
      '%s | cmd=%s | roles=%s | using=%s | with check=%s',
      case when p.permissive = 'PERMISSIVE' then 'permisiva' else 'restrictiva' end,
      p.cmd,
      array_to_string(p.roles, ','),
      coalesce(p.qual, '—'),
      coalesce(p.with_check, '—')
    ) as linea
  from pg_policies p
  join objetivo o on o.relname = p.tablename
  where p.schemaname = 'public'
),
permisos as (
  -- Sin GRANT no hay acceso, aunque la política RLS lo permita: las apps
  -- entran con el anon key, así que estos privilegios son parte del DDL.
  select
    g.table_name as tabla,
    g.grantee || '-' || g.privilege_type as orden,
    'grant ' || g.privilege_type || ' to ' || g.grantee as linea
  from information_schema.role_table_grants g
  join objetivo o on o.relname = g.table_name
  where g.table_schema = 'public'
    and g.grantee in ('anon', 'authenticated', 'service_role')
),
triggers as (
  select o.relname as tabla, t.tgname as orden, pg_get_triggerdef(t.oid) as linea
  from pg_trigger t
  join objetivo o on o.oid = t.tgrelid
  where not t.tgisinternal
)
select '1-COLUMNAS'    as seccion, tabla, orden, linea from columnas
union all select '2-CONSTRAINTS', tabla, orden, linea from constraints
union all select '3-INDICES',     tabla, orden, linea from indices
union all select '4-RLS',         tabla, orden, linea from rls_estado
union all select '4-RLS',         tabla, orden, linea from rls_politicas
union all select '5-PERMISOS',    tabla, orden, linea from permisos
union all select '6-TRIGGERS',    tabla, orden, linea from triggers
order by 1, 2, 3;


-- ══════════════════════════════════════════════════════════════════════
--  SECCIÓN B · Los mismos datos, sueltos
-- ══════════════════════════════════════════════════════════════════════
-- Correr uno a la vez; el SQL Editor muestra el resultado del último.

-- B1 · Columnas, tipo exacto, nullability y default
-- select a.attname, format_type(a.atttypid, a.atttypmod) as tipo,
--        a.attnotnull as not_null, pg_get_expr(ad.adbin, ad.adrelid) as default_
-- from pg_attribute a
-- join pg_class c on c.oid = a.attrelid
-- join pg_namespace n on n.oid = c.relnamespace
-- left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
-- where n.nspname = 'public' and c.relname = 'tickets'
--   and a.attnum > 0 and not a.attisdropped
-- order by a.attnum;

-- B2 · PK, FK, UNIQUE y CHECK
-- select conname, contype, pg_get_constraintdef(oid) as definicion
-- from pg_constraint
-- where conrelid = 'public.tickets'::regclass
-- order by contype, conname;

-- B3 · Índices
-- select indexname, indexdef from pg_indexes
-- where schemaname = 'public' and tablename in ('tickets','bitacora','cortes','empleados')
-- order by tablename, indexname;

-- B4 · RLS: interruptor de la tabla + políticas
-- select relname, relrowsecurity, relforcerowsecurity
-- from pg_class where oid in ('public.tickets'::regclass, 'public.bitacora'::regclass, 'public.cortes'::regclass, 'public.empleados'::regclass);
-- select tablename, policyname, permissive, cmd, roles, qual, with_check
-- from pg_policies
-- where schemaname = 'public' and tablename in ('tickets','bitacora','cortes','empleados')
-- order by tablename, policyname;

-- B5 · Privilegios del anon key
-- select table_name, grantee, privilege_type
-- from information_schema.role_table_grants
-- where table_schema = 'public' and table_name in ('tickets','bitacora','cortes','empleados')
--   and grantee in ('anon','authenticated','service_role')
-- order by table_name, grantee, privilege_type;


-- ══════════════════════════════════════════════════════════════════════
--  SECCIÓN C · Lo que el código espera encontrar
-- ══════════════════════════════════════════════════════════════════════
-- Inventario levantado leyendo las llamadas REST de los .html (no es el
-- esquema real: es lo que las apps escriben y leen). Sirve para dos cosas
-- al revisar la salida de la sección A: detectar una columna que el código
-- usa y en la base no existe, y detectar columnas en la base que ya nadie
-- usa. Si algo de esta lista NO aparece en la salida, hay deriva.
--
-- tickets — escrituras (IwolPark_TABLET.html syncOperacion + alta manual
-- del Dashboard Admin):
--   folio, tipo, estatus, cajero, cajero_entrada, cajero_salida, turno_id,
--   hora_entrada_at, hora_salida_at, hora_entrada, hora_salida,
--   minutos_estancia, horas_cobradas, tarifa, penalizacion, importe,
--   franja, folio_salida, fecha_op, dia_semana, mes, anio, plaza
-- tickets — agregadas después por migración:
--   pension_id (uuid, FK a pensiones — sql_pension_id_tickets.sql + _fk.sql)
--   empleado_id (bigint, FK a empleados — sql_empleado_id.sql)
--   folio_salida (text — sql_folio_salida.sql)
-- tickets — solo lectura: created_at (orden de Movimientos)
--
-- bitacora — escrituras (logBitacora, best-effort, nunca bloquea la caja):
--   plaza_id, usuario, accion, detalle, ip
-- bitacora — solo lectura: created_at (filtro y orden de la vista Bitácora)
--   `ip` la agregó sql_bitacora_ip.sql.
--
-- Valores que el código produce (para contrastar con los CHECK reales):
--   tickets.estatus : abierto, cobrado, perdido, cortesia, cancelado
--                     (+ 'cerrado_admin' en una ruta del Dashboard Admin)
--   tickets.tipo    : normal, preferencial, pension, empleado, cortesia, perdido
--   bitacora.accion : login, cobro, impresion, reimpresion_comprobante,
--                     cancelacion, captura_manual, arqueo, relevo, cierre_dia,
--                     cierre_manual_reconciliacion, cierre_automatico,
--                     cierre_administrativo, folio_leido, seleccion,
--                     atajo_teclado, vista_pantalla, promo_toggle,
--                     promo_campana_guardada, promo_campana_estado,
--                     promo_local_guardado
--
-- ⚠ Dato a confirmar en la salida: IwolPark_TABLET.html documenta que
-- `tickets` NO tiene UNIQUE(folio), y por eso enviarSupabase() hace
-- PATCH-por-folio y, si no actualizó nada, POST. Ese camino no es atómico:
-- dos peticiones casi simultáneas pueden insertar el mismo folio dos veces.
-- El propio código ya trae el manejo del error 23505 "para cuando la
-- constraint exista". Si la sección A confirma que no hay UNIQUE(folio),
-- crearla cierra ese hueco — pero antes hay que limpiar los duplicados que
-- ya existan, así que es una decisión con datos de por medio, no un simple
-- alter table.
